%% optimize: function description

function [Hopt] = optimize(u1, u2, H)
	
	cost = @(H) mean(reprojerror(u1, u2, H));
	
	options = optimoptions( ...
		'lsqnonlin', ...
		'Algorithm', 'levenberg-marquardt', ...
		'MaxIter', 1e3, ...
		'MaxFunEvals', 1e3, ...
		'Display', 'off' ...
	);

	Hopt = lsqnonlin(cost, H, [], [], options);
