function [handles] = initHandles(handles)

	keys = { ...
		'ObjTX', 'ObjTY', 'ObjTZ', ...
		'ObjRX', 'ObjRY', 'ObjRZ', ...
		'CamTX', 'CamTY', 'CamTZ', ...
		'CamRX', 'CamRY', 'CamRZ'  ...
	};

	rangeValues = [ ...
		{[-100, 100]}, {[-100, 100]}, {[-20, 130]},  ...
		{[-180, 180]}, {[-180, 180]}, {[-180, 180]}, ...
		{[-100, 100]}, {[-100, 100]}, {[-20, 130]},  ...
		{[-180, 180]}, {[-180, 180]}, {[-180, 180]}, ...
	];
	handles.ranges = containers.Map(keys, rangeValues);

	sliderValues = [ ...
		{'sliderObjTX'}, {'sliderObjTY'}, {'sliderObjTZ'}, ...
		{'sliderObjRX'}, {'sliderObjRY'}, {'sliderObjRZ'}, ...
		{'sliderCamTX'}, {'sliderCamTY'}, {'sliderCamTZ'}, ...
		{'sliderCamRX'}, {'sliderCamRY'}, {'sliderCamRZ'}, ...
	];
	handles.sliders = containers.Map(keys, sliderValues);

	editValues = [ ...
		{'editObjTX'}, {'editObjTY'}, {'editObjTZ'}, ...
		{'editObjRX'}, {'editObjRY'}, {'editObjRZ'}, ...
		{'editCamTX'}, {'editCamTY'}, {'editCamTZ'}, ...
		{'editCamRX'}, {'editCamRY'}, {'editCamRZ'}, ...
	];
	handles.edits = containers.Map(keys, editValues);
