function [] = plot_world(handles)

	axes(handles.worldFigure);
	trisurf(handles.object.F, ...
        	handles.object.V(1,:), ...
        	handles.object.V(2,:), ...
        	handles.object.V(3,:), ...
        	'FaceColor', 'r', 'EdgeColor', 'none');

	hold on

	trisurf(handles.camera.F, ...
        	handles.camera.V(1,:), ...
        	handles.camera.V(2,:), ...
        	handles.camera.V(3,:), ...
        	'FaceColor', 'b', 'EdgeColor', 'none');

	axis equal;
	axis(handles.world.axis);
