function [] = plotWorld (handles)

  Robj = ...
    Rz(str2num(get(handles.editObjRZ, 'String')))* ...
    Ry(str2num(get(handles.editObjRY, 'String')))* ...
    Rx(str2num(get(handles.editObjRX, 'String')));
  
  Tobj = T(...
    str2num(get(handles.editObjTX, 'String')), ...
    str2num(get(handles.editObjTY, 'String')), ...
    str2num(get(handles.editObjTZ, 'String')) ...
  );

  Vobj = Tobj*Robj*handles.object.V;

  Rcam = ...
    Rz(str2num(get(handles.editCamRZ, 'String')))* ...
    Ry(str2num(get(handles.editCamRY, 'String')))* ...
    Rx(str2num(get(handles.editCamRX, 'String')));
  
  Tcam = T(...
    str2num(get(handles.editCamTX, 'String')), ...
    str2num(get(handles.editCamTY, 'String')), ...
    str2num(get(handles.editCamTZ, 'String')) ...
  );

  Vcam = Tcam*Rcam*handles.camera.V;

  

  axes(handles.worldFigure);
  cla
  hold on
  axis equal;
  view([-25, 30])
  grid on;
  range = [handles.ranges('ObjTX'), handles.ranges('ObjTY'), handles.ranges('ObjTZ')];
  axis(range);

  trisurf(handles.object.F, ...
          Vobj(1,:), ...
          Vobj(2,:), ...
          Vobj(3,:), ...
          'FaceColor', 'r', 'EdgeColor', 'none');

  trisurf(handles.camera.F, ...
          Vcam(1,:), ...
          Vcam(2,:), ...
          Vcam(3,:), ...
          'FaceColor', 'b', 'EdgeColor', 'none');

  
