function R = Rodrigues(t,w)
w = w./norm(w);
w_hat = [   ...
            0,      -w(3),  w(2);...
            w(3),   0,      -w(1);...
            -w(2),  w(1),   0];
R = eye(3) + w_hat*sind(t) + (w_hat^2)*(1-cosd(t));